# Generated by Django 5.1 on 2024-09-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OASAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='answer',
        ),
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='material',
        ),
        migrations.DeleteModel(
            name='news',
        ),
        migrations.DeleteModel(
            name='program',
        ),
        migrations.DeleteModel(
            name='question',
        ),
        migrations.DeleteModel(
            name='response',
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.DeleteModel(
            name='year',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='Address',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contactno',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquirytext',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='address',
            field=models.TextField(default='support'),
            preserve_default=False,
        ),
    ]
