# Generated by Django 5.1 on 2024-09-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OASAPP', '0004_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('course_session', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=300)),
                ('course_fees', models.CharField(max_length=100)),
                ('course_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='number',
            field=models.IntegerField(),
        ),
    ]
