# Generated by Django 5.1 on 2024-09-15 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OASAPP', '0008_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
