# Generated by Django 5.1 on 2024-10-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OASAPP', '0009_delete_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
